dashboard:
  grafana:
    format: json
    template: grafana/files/grafana_dashboards/grafana_influxdb.json
  main:
    format: yaml
    base_dashboards: ['grafana:client:base_templates:main_dashboard']
    base_rows: ['grafana:client:base_templates:service_row']
    base_panels: ['grafana:client:base_templates:cluster_status_singlestat']
